SET NAMES utf8mb4;

ALTER TABLE productos
MODIFY COLUMN categoria ENUM(
    'Fertilizantes Sólidos',
    'Fertilizantes Complejos',
    'Fertilizantes Líquidos',
    'Fungicidas',
    'Insecticidas',
    'Feromona Asperjable',
    'Difusor Feromona',
    'Herbicidas',
    'Fertilizantes Especiales',
    'Fertilizantes Foliares',
    'Madera',
    'Postes Metálicos y ancla',
    'Totora',
    'Fertilizantes Orgánicos',
    'Herramientas menores',
    'Bioestimulantes Radioculares',
    'Hormiguicidas',
    'Sistemicos Peronóspera',
    'Plantas Vitis Vinifera',
    'Levadura SA',
    'Levadura SA Siembra Directa',
    'Levadura SA Bayanus',
    'Levadura SA TRB Genérico',
    'Levadura SA Tinto Verietal',
    'Levadura SA Blanco Varietal',
    'Levadura SA Dulce Natural',
    'Nutriente enologico',
    'Nutriente enológico',
    'Desincrustante',
    'Clarificante',
    'Acidulante',
    'Acido columna',
    'Enzima',
    'EPP (Elementos de protección personal )',
    'Indumentaria',
    'Calzado',
    'Elementos de limpieza',
    'Cañerias',
    'Accesorios',
    'Otros'
) NOT NULL DEFAULT 'Otros';
